const LOAD_USERS = 'LOAD_USERS';
const CREATE_USER = 'CREATE_USER';
const UPDATE_USER = 'UPDATE_USER';
const DESTROY_USER = 'DESTROY_USER';

export {
  LOAD_USERS,
  CREATE_USER,
  UPDATE_USER,
  DESTROY_USER
};
